resources:
  - name: gitRepo
    type: GitRepo
    configuration:
      path: itamarb/pipelines-download-files
      gitProvider: GitHub
      branches:
        include: main
    
pipelines:
  - name: download_example
    steps:
      - name: download_files
        type: Bash
        configuration:
          inputResources:
            - name: gitRepo
              trigger: false
          integrations:
            - name: myArtifactory
        execution:
          onStart:
            - retry_command jfrog rt config --url $int_myArtifactory_url --user $int_myArtifactory_user --apikey $int_myArtifactory_apikey --interactive=false
            - export JFROG_CLI_LOG_LEVEL=DEBUG 
            - jfrog rt dl --spec dependencyState/resources/gitRepo/specfile.json
